-- Day12 EDA 탐색용 샘플 데이터 100건
-- 사용법: Supabase SQL Editor에 붙여넣고 Run 버튼 클릭
-- 또는 로컬 개발 시 필요하면 실행

insert into applications (name, contact, subject, motivation, created_at)
values
('김철수', 'chulsu.kim@gmail.com', 'coding', '초등학생들에게 프로그래밍의 재미를 알려주고 싶습니다', now() - interval '45 days'),
('이민지', '010-1234-5678', 'basic', '기초 컴퓨터 활용능력을 가르쳐 보고 싶습니다', now() - interval '44 days'),
('박준호', 'junho.park@naver.com', 'digital-literacy', null, now() - interval '43 days'),
('정수진', '010-2345-6789', 'coding', '파이썬과 웹개발을 지도한 경험이 있습니다', now() - interval '42 days'),
('최은영', 'eunyoung@hotmail.com', 'basic', '학생들의 개별 진도에 맞춘 맞춤형 교육을 제공하고 싶습니다', now() - interval '41 days'),
('한동욱', '010-3456-7890', 'digital-literacy', null, now() - interval '40 days'),
('윤혜원', 'hyewon.yun@gmail.com', 'coding', '게임 프로그래밍과 알고리즘을 좋아합니다', now() - interval '39 days'),
('장민준', '010-4567-8901', 'basic', '성인 학습자들을 대상으로 한 강의 경험 있음', now() - interval '38 days'),
('신지원', 'jiwon.shin@naver.com', 'coding', null, now() - interval '37 days'),
('고재훈', '010-5678-9012', 'digital-literacy', '미디어 리터러시와 비판적 사고능력 교육에 관심', now() - interval '36 days'),
('강미리', 'miri.kang@gmail.com', 'basic', '누구나 배울 수 있는 쉬운 컴퓨터 사용법을 알려주고 싶습니다', now() - interval '35 days'),
('오상혁', '010-6789-0123', 'coding', '머신러닝과 인공지능 입문 교육에 자신 있습니다', now() - interval '34 days'),
('임지은', 'jieun.im@hotmail.com', 'digital-literacy', null, now() - interval '33 days'),
('전재현', '010-7890-1234', 'basic', '초보자를 위한 친절한 설명이 제 강점입니다', now() - interval '32 days'),
('류민경', 'minkyung.ryu@naver.com', 'coding', '자바스크립트와 리액트 강의 경험 5년', now() - interval '31 days'),
('배지훈', '010-8901-2345', 'basic', null, now() - interval '30 days'),
('조예진', 'yejin.jo@gmail.com', 'digital-literacy', '소셜미디어 안전 교육에 관심이 많습니다', now() - interval '29 days'),
('유현동', '010-9012-3456', 'coding', '파이썬 데이터 분석과 시각화를 전공했습니다', now() - interval '28 days'),
('송은진', 'eunji.song@naver.com', 'basic', '비즈니스 문서 작성 및 엑셀 강의 경험', now() - interval '27 days'),
('현지훈', '010-0123-4567', 'digital-literacy', null, now() - interval '26 days'),
('이소연', 'soyeon.lee@gmail.com', 'coding', '앱 개발과 크로스플랫폼 강의를 제공합니다', now() - interval '25 days'),
('경준수', '010-1234-5679', 'basic', '직장인들을 위한 업무 효율화 교육', now() - interval '24 days'),
('김하윤', 'hayun.kim@hotmail.com', 'coding', null, now() - interval '23 days'),
('박소정', '010-2345-6780', 'digital-literacy', '인터넷 윤리와 정보보안 교육에 전문성 있음', now() - interval '22 days'),
('최도현', 'dohyun.choi@naver.com', 'basic', '시니어층을 대상으로 한 컴퓨터 기초 교육', now() - interval '21 days'),
('홍진욱', '010-3456-7891', 'coding', 'C++과 자료구조 강의 경험 있습니다', now() - interval '20 days'),
('전지연', 'jiyeon.jeon@gmail.com', 'digital-literacy', null, now() - interval '19 days'),
('강현우', '010-4567-8902', 'basic', '학생 개개인의 학습 수준에 맞춘 교육', now() - interval '18 days'),
('노유진', 'yujin.noh@naver.com', 'coding', '웹 풀스택 개발과 클라우드 아키텍처', now() - interval '17 days'),
('서민호', '010-5678-9013', 'basic', null, now() - interval '16 days'),
('우정현', 'junghyun.woo@hotmail.com', 'digital-literacy', '디지털 격차 해소를 위한 교육에 헌신적', now() - interval '15 days'),
('조준희', '010-6789-0124', 'coding', '모바일 앱 개발과 게임 프로그래밍 경험', now() - interval '14 days'),
('이진성', 'jinseong.lee@gmail.com', 'basic', '엑셀 매크로와 자동화 교육 전문', now() - interval '13 days'),
('한소영', '010-7890-1235', 'digital-literacy', null, now() - interval '12 days'),
('양경수', 'kyungsoo.yang@naver.com', 'coding', '블록체인과 스마트컨트랙트 입문 강의', now() - interval '11 days'),
('문나영', '010-8901-2346', 'basic', '친절하고 명확한 설명으로 정평이 있습니다', now() - interval '10 days'),
('김태희', 'taehee.kim@hotmail.com', 'coding', null, now() - interval '9 days'),
('박영우', '010-9012-3457', 'digital-literacy', '온라인 플랫폼 안전 교육 경험 많음', now() - interval '8 days'),
('신준호', 'junho.shin@gmail.com', 'basic', '컴퓨터 기초부터 심화까지 가능합니다', now() - interval '7 days'),
('유지호', '010-0123-4568', 'coding', '자료구조와 알고리즘 전문 강사', now() - interval '6 days'),
('이여정', 'yeojung.lee@naver.com', 'digital-literacy', null, now() - interval '5 days'),
('호정민', '010-1234-5680', 'basic', '노년층 대상 기초 컴퓨터 교육', now() - interval '4 days'),
('강세운', 'sewun.kang@hotmail.com', 'coding', '파이썬 크롤링과 자동화 강의', now() - interval '3 days'),
('최성희', '010-2345-6781', 'basic', null, now() - interval '2 days'),
('정승현', 'seunghyun.jung@gmail.com', 'digital-literacy', '미디어 리터러시 교육으로 학생들의 비판적 사고력 향상', now() - interval '1 days'),
('박선미', '010-3456-7892', 'coding', '데이터 분석과 머신러닝 입문 과정 강의', now()),
('김유나', 'yuna.kim@naver.com', 'basic', '성인 학습자들을 위한 친절한 컴퓨터 기초', now() - interval '30 hours'),
('이준형', '010-4567-8903', 'digital-literacy', null, now() - interval '29 hours'),
('송미영', 'miyoung.song@hotmail.com', 'coding', 'IoT와 아두이노 프로젝트 교육', now() - interval '28 hours'),
('강다혜', '010-5678-9014', 'basic', '학생 맞춤형 교육 프로그램 운영 경험', now() - interval '27 hours'),
('우준영', 'junyoung.woo@gmail.com', 'digital-literacy', null, now() - interval '26 hours'),
('채지은', '010-6789-0125', 'coding', 'AWS 클라우드와 백엔드 개발 경험', now() - interval '25 hours'),
('현승훈', 'seunghun.hyun@naver.com', 'basic', '초등학생을 위한 재미있는 컴퓨터 수업', now() - interval '24 hours'),
('노예은', '010-7890-1236', 'coding', null, now() - interval '23 hours'),
('김준석', 'junseok.kim@hotmail.com', 'digital-literacy', '정보 보안과 개인정보보호 교육 전문', now() - interval '22 hours'),
('박혜정', '010-8901-2347', 'basic', '오피스 소프트웨어 완벽 마스터 강의', now() - interval '21 hours'),
('이순재', 'sounjae.lee@gmail.com', 'coding', '웹 디자인과 UI/UX 개발 경험 풍부', now() - interval '20 hours'),
('정민정', '010-9012-3458', 'digital-literacy', null, now() - interval '19 hours'),
('홍지선', 'jisun.hong@naver.com', 'basic', '컴퓨터 공포증 극복 프로그램 운영', now() - interval '18 hours'),
('조철희', '010-0123-4569', 'coding', '리눅스와 쉘 스크립트 강의', now() - interval '17 hours'),
('윤소정', 'sojung.yun@hotmail.com', 'digital-literacy', null, now() - interval '16 hours'),
('강준혁', '010-1234-5681', 'basic', '세대별 맞춤 컴퓨터 교육', now() - interval '15 hours'),
('이민철', 'minchul.lee@gmail.com', 'coding', 'R과 통계 분석 강의 경험', now() - interval '14 hours'),
('김지은', '010-2345-6782', 'digital-literacy', '온라인 수업과 원격 교육 전문', now() - interval '13 hours'),
('박준영', 'junyoung.park@naver.com', 'basic', null, now() - interval '12 hours'),
('최윤희', '010-3456-7893', 'coding', '프론트엔드 개발과 웹 표준 강의', now() - interval '11 hours'),
('신예지', 'yeji.shin@hotmail.com', 'digital-literacy', '청소년 사이버폭력 예방 교육', now() - interval '10 hours'),
('유현준', '010-4567-8904', 'basic', '비즈니스 실무 중심 컴퓨터 교육', now() - interval '9 hours'),
('이채영', 'chaeyoung.lee@gmail.com', 'coding', null, now() - interval '8 hours'),
('홍민준', '010-5678-9015', 'digital-literacy', '정보통신윤리와 사이버 안전', now() - interval '7 hours'),
('강소영', 'soyoung.kang@naver.com', 'basic', '직장인 업무 자동화 교육 전문', now() - interval '6 hours'),
('박지훈', '010-6789-0126', 'coding', '게임 엔진 활용과 3D 프로그래밍', now() - interval '5 hours'),
('이소정', 'sojung.lee@hotmail.com', 'digital-literacy', null, now() - interval '4 hours'),
('정준호', '010-7890-1237', 'basic', '학생들의 학습 진행 상황을 세심하게 관리', now() - interval '3 hours'),
('윤지훈', 'jihun.yun@gmail.com', 'coding', '닷넷과 C# 프로그래밍 강의', now() - interval '2 hours'),
('노준영', '010-8901-2348', 'digital-literacy', null, now() - interval '1 hours'),
('김나영', 'nayoung.kim@naver.com', 'basic', '컴퓨터 초보자를 위한 친절한 설명력이 우수', now()),
('박동욱', '010-9012-3459', 'coding', '모바일 웹앱 개발과 반응형 디자인', now() - interval '40 hours'),
('이예준', 'yejun.lee@hotmail.com', 'digital-literacy', '디지털 시대의 올바른 정보 활용 교육', now() - interval '39 hours'),
('성현주', '010-0123-4570', 'basic', null, now() - interval '38 hours'),
('최진욱', 'jinwook.choi@gmail.com', 'coding', 'SQL과 데이터베이스 설계 강의', now() - interval '37 hours'),
('한미소', '010-1234-5682', 'digital-literacy', '소셜미디어 현명하게 사용하기 교육', now() - interval '36 hours'),
('조수빈', 'subin.jo@naver.com', 'basic', '고령층 컴퓨터 기초 교실 운영 경험', now() - interval '35 hours'),
('우준호', '010-2345-6783', 'coding', null, now() - interval '34 hours'),
('이지환', 'jihwan.lee@hotmail.com', 'digital-literacy', '온라인 커뮤니티 건강 교육', now() - interval '33 hours');

-- 검증 쿼리: 삽입된 데이터 확인
-- select count(*) as total, count(distinct subject) as subjects from applications;
-- select subject, count(*) from applications group by subject;
